const GETDATA = "GETDATA"
const CHANGESELECT = "CHANGESELECT"
const CHANGESELECTALL = "CHANGESELECTALL"
const CHANGENUMBER = "CHANGENUMBER"
export{
    GETDATA,
    CHANGESELECT,
    CHANGESELECTALL,
    CHANGENUMBER
}