const GETDATA = "GETDATA"
const CHANGESELECT = "CHANGESELECT"
const CHANGESELECTALL = "CHANGESELECTALL"
const CHANGENUMBER = "CHANGENUMBER"
const DEL = "DEL"
export{
    GETDATA,
    CHANGESELECT,
    CHANGESELECTALL,
    CHANGENUMBER,
    DEL
}